import { Navbar } from '@/components/Navbar'
import { Footer } from '@/components/Footer'

// Local typography helpers — this page is mostly prose, so repeating the
// className strings inline would triple its length.
const H = ({ children }: { children: React.ReactNode }) =>
  <h2 className="text-base font-semibold text-foreground mt-8 mb-2">{children}</h2>
const P = ({ children }: { children: React.ReactNode }) =>
  <p className="text-sm text-muted-foreground leading-relaxed mb-3">{children}</p>
const B = ({ children }: { children: React.ReactNode }) =>
  <span className="text-foreground font-medium">{children}</span>

const Table = ({ rows }: { rows: [string, string][] }) => (
  <div className="overflow-x-auto my-3">
    <table className="w-full text-sm border-collapse">
      <thead>
        <tr className="border-b border-border/60">
          <th className="text-left py-2 pr-4 font-medium text-foreground whitespace-nowrap">Data</th>
          <th className="text-left py-2 font-medium text-foreground">Purpose</th>
        </tr>
      </thead>
      <tbody>
        {rows.map(([data, purpose]) => (
          <tr key={data} className="border-b border-border/40 align-top">
            <td className="py-2 pr-4 text-foreground whitespace-nowrap">{data}</td>
            <td className="py-2 text-muted-foreground leading-relaxed">{purpose}</td>
          </tr>
        ))}
      </tbody>
    </table>
  </div>
)

export default function Privacy() {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Navbar />

      <main className="max-w-2xl mx-auto px-4 pt-24 pb-20 flex-1 w-full">
        <h1 className="text-3xl font-bold text-foreground tracking-tight">Privacy Policy</h1>
        <p className="text-muted-foreground mt-2 text-base">Last updated: August 25, 2026</p>

        <div className="mt-8">
          <P>
            Agentic Flight Finder ("the Service") is a free, non-commercial personal project
            operated by an individual. This policy explains what data the Service collects, why,
            who it is shared with, and how to have it deleted.
          </P>
          <P>
            Questions or requests:{' '}
            <a href="mailto:agenticflightfinder@gmail.com" className="text-accent hover:text-accent/80">
              agenticflightfinder@gmail.com
            </a>
          </P>

          <H>The short version</H>
          <ul className="text-sm text-muted-foreground leading-relaxed space-y-1.5 list-disc pl-5 mb-3">
            <li>The Service collects your email address, the flight preferences you enter, and the price data it gathers on your behalf.</li>
            <li>There is <B>no advertising</B> on this site.</li>
            <li>The Service may analyze route and usage data in aggregate to understand how it is used and improve it. Section 2 explains what that does and does not involve.</li>
            <li>Your monitors are run by an AI agent (Claude, by Anthropic). Section 3 explains exactly what it does and does not receive.</li>
            <li>Your data is <B>never sold, rented, or shared for marketing purposes</B>.</li>
            <li>You can have your account and all associated data deleted by emailing the address above.</li>
          </ul>

          <H>1. What the Service collects</H>
          <P><B>Information you provide</B></P>
          <Table rows={[
            ['Email address', 'To identify your account and deliver flight alerts'],
            ['Password', 'To authenticate you. Handled by Supabase and stored only as a salted hash — the operator of this Service cannot see or recover your password'],
            ['Flight preferences', 'Origin and destination airports, travel periods, budget, cabin class, stop limits, date flexibility, and alert frequency — used to run your monitor'],
            ['"Additional context" free text', 'An optional field passed to the AI agent so it can weigh your preferences. See Section 3 before entering anything here'],
          ]} />

          <P><B>Information generated by the Service</B></P>
          <Table rows={[
            ['Price history', 'Fares found for your routes, timestamped, so the agent can judge whether a price is good'],
            ['Alerts', "The alerts sent to you, including the AI's written reasoning, so you can review them in-app"],
            ['Activity log', 'A record of each agent run and the decision it made, kept as an audit trail'],
          ]} />

          <P><B>Information collected automatically</B></P>
          <Table rows={[
            ['IP address', 'Used transiently for rate limiting to prevent abuse. The Service does not store IP addresses in its database or link them to your account, though the hosting provider’s own access logs may record them'],
            ['Server logs', "Standard operational logs from the hosting provider, used for debugging and kept only for the provider's default retention period"],
          ]} />

          <H>2. How the Service uses your data, and what it does not collect</H>
          <P>
            Beyond running your monitors, the Service may analyze the data described in Section 1 —
            such as which routes are searched most often — in aggregate, to understand how the
            Service is used and to improve it. This analysis is performed on data already held in
            the Service's own database.
          </P>
          <P>To be explicit about the limits of that, because most privacy policies bury this:</P>
          <ul className="text-sm text-muted-foreground leading-relaxed space-y-1.5 list-disc pl-5 mb-3">
            <li><B>No advertising cookies or ad networks.</B></li>
            <li><B>No payment information.</B> The Service is free and does not process payments.</li>
            <li><B>No location data</B>, beyond the airport codes you type in yourself.</li>
            <li><B>No contacts, no device fingerprinting, and no data collected about you from other websites.</B></li>
            <li><B>Aggregate analysis is not sold or shared.</B> It is used only to operate and improve the Service.</li>
          </ul>
          <P>
            If the Service ever adds third-party analytics or tracking technology, this policy will be
            updated to say so before it is enabled, and any consent required by law will be requested
            at that time.
          </P>

          <H>3. Who your data is shared with</H>
          <P>The Service relies on the third-party providers below. Each receives only what it needs to do its job.</P>
          <P>
            <B>Supabase</B> — database, authentication, and account storage. Holds your email,
            password hash, preferences, price history, and alerts. Access is restricted at the
            database level by Row Level Security, so one account cannot read another account's data.
          </P>
          <P>
            <B>Anthropic (Claude)</B> — the AI agent that runs your monitors. Every decision the
            Service makes on your behalf — whether to search, how to judge a price, whether to alert
            you — is made by an AI model (<code className="font-mono text-xs text-foreground">claude-haiku-4-5</code>),
            not by a person. To do this, Claude receives your flight preference record on each run:
            route, dates, budget, cabin class, alert frequency, your "additional context" text, and
            an internal account identifier, along with your recent activity and alert history. It
            does <B>not</B> receive your email address, your name, or your password. Because your
            "additional context" text is sent to Anthropic, please avoid entering sensitive personal
            information there — health details, financial details, government identifiers, or
            information about other people.
          </P>
          <P>
            <B>An email delivery provider</B> — used to send your alerts. Receives your email address
            and the contents of the alert being sent to you.
          </P>
          <P><B>Railway</B> — hosting for the application and its server logs.</P>
          <P>
            <B>Flight data source</B> — searches are sent as route, date, and cabin class only.{' '}
            <B>No user identity, account identifier, or email address is ever sent to the flight
            data source.</B> It cannot tell who a search is for.
          </P>
          <P>
            Your data is not shared with anyone else. It is <B>not sold, not rented, and not shared
            for advertising or marketing</B>, and the Service will never do so. If that ever changes,
            this policy will be updated before the change takes effect.
          </P>
          <P>The Service may disclose information if legally required to do so by valid legal process.</P>

          <H>4. Cookies and local storage</H>
          <P>
            The Service stores a single authentication session token in your browser's local storage.
            This is what keeps you signed in.
          </P>
          <P>
            This is a <B>strictly necessary</B> item — it exists only to deliver the service you asked
            for, contains no tracking identifier, and is not shared with anyone. The Service currently
            sets no advertising cookies and no third-party cookies. Clearing your browser storage will
            simply sign you out.
          </P>

          <H>5. How long data is kept</H>
          <P>
            Your account data and preferences are kept for as long as your account exists. Price
            history and alerts are retained so the agent can reason about long-term price trends,
            which is the core of how the Service works.
          </P>
          <P>When you request deletion, everything is removed as described below.</P>

          <H>6. Your choices and how to delete your data</H>
          <P>You can, at any time:</P>
          <ul className="text-sm text-muted-foreground leading-relaxed space-y-1.5 list-disc pl-5 mb-3">
            <li><B>Deactivate a monitor</B> in the app to stop it running and stop its alerts.</li>
            <li><B>Request a copy of your data</B> by email.</li>
            <li><B>Request full deletion of your account and all associated data</B> by email.</li>
          </ul>
          <P>
            To make a request, email{' '}
            <a href="mailto:agenticflightfinder@gmail.com" className="text-accent hover:text-accent/80">
              agenticflightfinder@gmail.com
            </a>{' '}
            from the address associated with your account. Requests are honored as promptly as is
            reasonably possible. Deletion removes your account, preferences, price history, alerts,
            and activity logs, and cannot be undone.
          </P>

          <H>7. Security</H>
          <P>
            Passwords are hashed by Supabase and are not visible to the operator. Database access is
            restricted per-account by Row Level Security, and the scheduled agent runs with
            credentials separate from those used to serve web requests.
          </P>
          <P>
            No system is perfectly secure, and the Service is a personal project rather than a
            hardened commercial platform. Please use a unique password that you do not reuse elsewhere.
          </P>

          <H>8. If there is a data breach</H>
          <P>
            If the Service becomes aware of a breach affecting your personal information, you will
            be notified by email as soon as is reasonably practicable. Relevant authorities will be
            notified where the law requires it.
          </P>

          <H>9. Children</H>
          <P>
            The Service is not intended for anyone under 13 and is not directed at children. If you
            believe a child under 13 has created an account, email the address above and it will be deleted.
          </P>

          <H>10. Where the Service operates</H>
          <P>
            The Service is operated from the United States and is intended for users in the United
            States. Data is processed and stored in the United States by the providers named in
            Section 3. The Service is not directed at or marketed to users in the European Union or
            United Kingdom.
          </P>

          <H>11. No affiliation</H>
          <P>
            Agentic Flight Finder is not affiliated with, endorsed by, or sponsored by any airline,
            Google, or any flight booking service. Airline names are used only to identify flights.
          </P>

          <H>12. Changes to this policy</H>
          <P>
            This policy may be updated from time to time. When it changes, the date at the top of
            this page is updated. Continued use after a change means you accept the updated policy,
            so please check back occasionally.
          </P>

          <H>13. Contact</H>
          <P>
            <a href="mailto:agenticflightfinder@gmail.com" className="text-accent hover:text-accent/80">
              agenticflightfinder@gmail.com
            </a>
          </P>
        </div>
      </main>

      <Footer />
    </div>
  )
}
